flat_full.Rmd:
  path: dev/flat_full.Rmd
  state: active
  R:
  - R/check_spectra.R
  - R/import_biotyper_spectra.R
  - R/read_biotyper_report.R
  - R/read_many_biotyper_reports.R
  tests:
  - tests/testthat/test-read_biotyper_report.R
  - tests/testthat/test-read_many_biotyper_reports.R
  - tests/testthat/test-import_biotyper_spectra.R
  - tests/testthat/test-check_spectra.R
  vignettes: vignettes/import-data-from-bruker-maldi-biotyper.Rmd
flat_process_spectra.Rmd:
  path: dev/flat_process_spectra.Rmd
  state: active
  R:
  - R/merge_processed_spectra.R
  - R/process_spectra.R
  tests:
  - tests/testthat/test-process_spectra.R
  - tests/testthat/test-merge_processed_spectra.R
  vignettes: vignettes/dereplicate-bruker-maldi-biotyper-spectra.Rmd
