dereplicate-spectra.Rmd:
  path: dev/dereplicate-spectra.Rmd
  state: active
  R:
  - R/delineate_with_identification.R
  - R/delineate_with_similarity.R
  - R/import_spede_clusters.R
  - R/merge_processed_spectra.R
  - R/pick_spectra.R
  - R/process_spectra.R
  - R/set_reference_spectra.R
  tests:
  - tests/testthat/test-process_spectra.R
  - tests/testthat/test-merge_processed_spectra.R
  - tests/testthat/test-delineate_with_similarity.R
  - tests/testthat/test-delineate_with_identification.R
  - tests/testthat/test-import_spede_clusters.R
  - tests/testthat/test-pick_spectra.R
  - tests/testthat/test-set_reference_spectra.R
  vignettes: vignettes/dereplicate-bruker-maldi-biotyper-spectra.Rmd
  inflate:
    flat_file: dev/dereplicate-spectra.Rmd
    vignette_name: Dereplicate Bruker MALDI Biotyper spectra
    open_vignette: true
    check: true
    document: true
    overwrite: ask
flat_utils.Rmd:
  path: dev/flat_utils.Rmd
  state: active
  R:
  - R/is_a_processed_spectra_list.R
  - R/is_a_rds_list.R
  - R/is_well_on_edge.R
  - R/get_spectra_names.R
  tests:
  - tests/testthat/test-is_well_on_edge.R
  - tests/testthat/test-is_a_rds_list.R
  - tests/testthat/test-is_a_processed_spectra_list.R
  - tests/testthat/test-get_spectra_names.R
  vignettes: []
  inflate:
    flat_file: dev/flat_utils.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: ask
import-data.Rmd:
  path: dev/import-data.Rmd
  state: active
  R:
  - R/check_spectra.R
  - R/import_biotyper_spectra.R
  - R/read_biotyper_report.R
  - R/read_many_biotyper_reports.R
  tests:
  - tests/testthat/test-read_biotyper_report.R
  - tests/testthat/test-read_many_biotyper_reports.R
  - tests/testthat/test-import_biotyper_spectra.R
  - tests/testthat/test-check_spectra.R
  vignettes: vignettes/import-data-from-bruker-maldi-biotyper.Rmd
  inflate:
    flat_file: dev/import-data.Rmd
    vignette_name: Import data from Bruker MALDI Biotyper
    open_vignette: true
    check: true
    document: true
    overwrite: ask
keep:
  path: keep
  state: active
  R:
  - R/gather_spectra_stats.R
  - R/remove_spectra_logical.R
  - R/remove_spectra.R
  - R/maldipickr-package.R
  - R/utils-pipe.R
  tests:
  - tests/testthat/test-gather_spectra_stats.R
  - tests/testthat/test-remove_spectra_logical.R
  - tests/testthat/test-remove_spectra.R
  vignettes: []
maldipickr.Rmd:
  path: dev/maldipickr.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/maldipickr.Rmd
  inflate:
    flat_file: dev/maldipickr.Rmd
    vignette_name: maldipickr
    open_vignette: true
    check: false
    document: true
    overwrite: ask
