dereplicate-spectra.Rmd:
  path: dev/dereplicate-spectra.Rmd
  state: active
  R:
  - R/import_spede_clusters.R
  - R/merge_processed_spectra.R
  - R/pick_spectra.R
  - R/process_spectra.R
  - R/set_reference_spectra.R
  - R/similarity_to_clusters.R
  tests:
  - tests/testthat/test-process_spectra.R
  - tests/testthat/test-merge_processed_spectra.R
  - tests/testthat/test-similarity_to_clusters.R
  - tests/testthat/test-set_reference_spectra.R
  - tests/testthat/test-import_spede_clusters.R
  - tests/testthat/test-pick_spectra.R
  vignettes: vignettes/b-dereplicate-bruker-maldi-biotyper-spectra.Rmd
  inflate:
    flat_file: dev/dereplicate-spectra.Rmd
    vignette_name: B-dereplicate-bruker-maldi-biotyper-spectra
    open_vignette: true
    check: true
    document: true
    overwrite: ask
flat_utils.Rmd:
  path: dev/flat_utils.Rmd
  state: active
  R:
  - R/is_a_processed_spectra_list.R
  - R/is_a_rds_list.R
  - R/is_well_on_edge.R
  tests:
  - tests/testthat/test-is_well_on_edge.R
  - tests/testthat/test-is_a_rds_list.R
  - tests/testthat/test-is_a_processed_spectra_list.R
  vignettes: []
import-data.Rmd:
  path: dev/import-data.Rmd
  state: active
  R:
  - R/check_spectra.R
  - R/import_biotyper_spectra.R
  - R/read_biotyper_report.R
  - R/read_many_biotyper_reports.R
  tests:
  - tests/testthat/test-read_biotyper_report.R
  - tests/testthat/test-read_many_biotyper_reports.R
  - tests/testthat/test-import_biotyper_spectra.R
  - tests/testthat/test-check_spectra.R
  vignettes: vignettes/a-import-data-from-bruker-maldi-biotyper.Rmd
  inflate:
    flat_file: dev/import-data.Rmd
    vignette_name: A-import-data-from-bruker-maldi-biotyper
    open_vignette: true
    check: true
    document: true
    overwrite: ask
