dereplicate-spectra.Rmd:
  path: dev/dereplicate-spectra.Rmd
  state: active
  R:
  - R/import_spede_clusters.R
  - R/merge_processed_spectra.R
  - R/process_spectra.R
  - R/similarity_to_clusters.R
  tests:
  - tests/testthat/test-process_spectra.R
  - tests/testthat/test-merge_processed_spectra.R
  - tests/testthat/test-similarity_to_clusters.R
  - tests/testthat/test-import_spede_clusters.R
  vignettes: vignettes/b-dereplicate-bruker-maldi-biotyper-spectra.Rmd
import-data.Rmd:
  path: dev/import-data.Rmd
  state: active
  R:
  - R/check_spectra.R
  - R/import_biotyper_spectra.R
  - R/read_biotyper_report.R
  - R/read_many_biotyper_reports.R
  tests:
  - tests/testthat/test-read_biotyper_report.R
  - tests/testthat/test-read_many_biotyper_reports.R
  - tests/testthat/test-import_biotyper_spectra.R
  - tests/testthat/test-check_spectra.R
  vignettes: vignettes/a-import-data-from-bruker-maldi-biotyper.Rmd
