---
title: "flat_process_spectra.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Process Bruker MALDI Biotyper spectra

```{r function-process_spectra}
#' Process Bruker MALDI Biotyper spectra _à la_ Strejcek et al. (2018)
#'
#' @details
#' Based on the original implementation, the function performs the following tasks:
#'
#' 1. Square-root transformation
#' 2. Mass range trimming to 4-10 kDA
#' 3. Signal smoothing
#' 4. Baseline Correction
#' 5. Normalisation
#' 6. Peak detection
#' 7. Peak filtering. This step has been added to discard peaks with a negative signal-to-noise ratio probably due to being on the edge of the mass range.
#'
#'
#' @param spectra_list A list of [MALDIquant::MassSpectrum] objects.
#' @param rds_prefix A character indicating the prefix for the `.RDS` output files to be written in the `processed` directory. By default, no prefix are given and thus no files are written.
#'
#' @return A named list of three objects:
#' * `spectra`: a list the length of the spectra list of [MALDIquant::MassSpectrum] objects.
#' * `peaks`: a list the length of the spectra list of [MALDIquant::MassPeaks] objects.
#' * `metadata`: a data frame indicating the median signal-to-noise ratio and peaks number for all spectra list, with their names as rownames.
#' @export
#'
#' @references Strejcek, Michal, Tereza Smrhova, Petra Junkova, and Ondrej Uhlik. “Whole-Cell MALDI-TOF MS versus 16S rRNA Gene Analysis for Identification and Dereplication of Recurrent Bacterial Isolates.” *Frontiers in Microbiology* 9 (2018). <https://doi.org/10.3389/fmicb.2018.01294>.
#'
#' @seealso [import_biotyper_spectra]
#' @note The original R code on which this function is based is accessible at: <https://github.com/strejcem/MALDIvs16S>
#' @examples
process_spectra <- function(spectra_list, rds_prefix = NULL) {
  # It returns the list and write it for future processing as an RDS file.

  # 1. SQRT transformation
  # 2. Mass range trimming
  # 3. Signal smoothing
  # 4. Baseline Correction
  # 5. Normalisation
  spectra <- spectra_list %>%
    MALDIquant::transformIntensity("sqrt") %>%
    MALDIquant::trim(range = c(4000, 10000)) %>%
    MALDIquant::smoothIntensity("SavitzkyGolay", halfWindowSize = 20) %>%
    MALDIquant::removeBaseline("SNIP", iterations = 50) %>%
    MALDIquant::calibrateIntensity(method = "TIC")

  # 6. Peak detection
  peaks <- spectra %>%
    MALDIquant::detectPeaks(
      method = "SuperSmoother",
      halfWindowSize = 20,
      SNR = 3
    )
  # Added extra step to remove the peaks with
  # negative SNR due to being on the edge of the masses trimmed
  peaks <- sapply(peaks, function(pk) {
    pk[MALDIquant::snr(pk) >= 3]
  })

  # Spectrum metadata table
  # Extract signal-to-noise ratios and peaks number
  metadata <- as.data.frame(t(sapply(peaks, function(x) {
    c(
      "SNR" = stats::median(MALDIquant::snr(x)),
      "peaks" = length(MALDIquant::snr(x))
    )
  })))

  # Add the spectra identifiers to all objects
  rownames(metadata) <- names(spectra) <- names(peaks) <- sapply(spectra, function(x) {
    # e.g., 230117_1750_1_B1
    gsub(
      "[-\\.]", "_",
      MALDIquant::metaData(x)[["fullName"]]
    )
  })
  # Aggregate the objects to a list
  processed_list <- list(
    "spectra" = spectra,
    "peaks" = peaks,
    "metadata" = metadata
  )

  # Optional: writing objects to RDS files
  if (!is.null(rds_prefix)) {
    if (!dir.exists("processed")) {
      dir.create("processed")
    }
    saveRDS(processed_list,
      version = 2, compress = FALSE,
      file = paste0("processed/", rds_prefix, ".RDS")
    )
  }
  return(processed_list)
}
```

```{r examples-process_spectra}
directory_for_biotyper_spectra <- system.file("toy-species-spectra", package = "maldipickr")
spectra_list <- import_biotyper_spectra(directory_for_biotyper_spectra)
processed <- process_spectra(spectra_list)
str(processed, max.level = 2)
processed$metadata
```

```{r tests-process_spectra}
directory_for_biotyper_spectra <- system.file("toy-species-spectra", package = "maldipickr")
spectra_list_test <- import_biotyper_spectra(directory_for_biotyper_spectra)[1:2]
test_that("process_spectra works", {
  expect_equal(
    process_spectra(spectra_list_test)$metadata,
    structure(
      list(
        SNR = c(5.08959045014141, 5.54373537030499),
        peaks = c(21, 22)
      ),
      class = "data.frame",
      row.names = c("species1_G2", "species2_E11")
    )
  )
})
test_that("process_spectra warns on empty spectra", {
  expect_warning(
    process_spectra(c(MALDIquant::createMassSpectrum(0, 0))),
    "MassSpectrum object is empty"
  )
})
```

# Merge multiples processed spectra
    
```{r function-merge_processed_spectra}
#' Merge multiples processed spectra and peaks
#'
#' Aggregate multiple processed spectra, their associated peaks and metadata into a feature matrix and a concatenated metadata table.
#'
#' @param processed_spectra A [list] The processed spectra and associated peaks and metadata in two possible formats:
#' * A vector of character that are the list of RDS files produced by [process_spectra].
#' * A named list of in-memory objects (named `spectra`, `peaks`, `metadata`) produced by [process_spectra].
#' @param remove_peakless_spectra A logical indicating whether to discard the spectra without detected peaks.
#' @param interpolate_missing A logical indicating if intensity values for missing peaks should be interpolated from the processed spectra signal or left NA which would then be converted to 0.
#'
#' @return A $n \times p$ matrix, with $n$ spectra and $p$ features that are the peaks found in all the processed spectra.
#'
#' @seealso [process_spectra], the "Value" section in [MALDIquant::intensityMatrix]
#' @export
merge_processed_spectra <- function(processed_spectra, remove_peakless_spectra = TRUE, interpolate_missing = TRUE) {
  # Determine the type of input
  processed <- switch(typeof(processed_spectra),
    "character" = lapply(processed_spectra, read_rds),
    "list" = processed_spectra
  )
  peakless <- list()
  # List the spectra with no peaks detected and remove them
  if (remove_peakless_spectra) {
    peakless <- lapply( # Extract the metadata object from all element of the list
      processed, `[[`, "metadata"
    ) %>%
      lapply(function(mdata) {
        rownames(mdata)[mdata$peaks == 0]
      }) %>%
      unlist()
    if (length(peakless) > 0) {
      warning(
        "No peaks were detected in the following spectra, so they will be removed\n",
        paste(peakless, collapse = "\n"), "\n"
      )
    }
  }

  # 7. Bin peaks
  peaks <- lapply( # Extract the peaks object from all element of the list
    processed, `[[`, "peaks"
  ) %>% unlist()
  names_spectra <- names(peaks)
  if (remove_peakless_spectra & length(peakless) > 0) {
    peaks <- peaks[-which(names(peaks) %in% peakless)]
  }
  peaks <- MALDIquant::binPeaks(peaks, tolerance = .002, method = "strict")

  # 8. Feature matrix construction (peaks as columns and spectra as rows)
  if (interpolate_missing) {
    # This is the default in the Strejcek et al. (2018) procedure
    spectra_list <- lapply( # Extract the spectrum object from all element of the list
      processed, `[[`, "spectra"
    ) %>% unlist()

    if (remove_peakless_spectra & length(peakless) > 0) {
      spectra_list <- spectra_list[-which(names(spectra_list) %in% peakless)]
    }
    featureMatrix <- MALDIquant::intensityMatrix(peaks, spectra_list)
  } else {
    featureMatrix <- MALDIquant::intensityMatrix(peaks)
    featureMatrix[is.na(featureMatrix)] <- 0
  }
  # Adding the correct rownames to the matrix
  if (remove_peakless_spectra & length(peakless) > 0) {
    rownames(featureMatrix) <- names_spectra[-which(names_spectra %in% peakless)]
  } else {
    rownames(featureMatrix) <- names_spectra
  }
  return(featureMatrix)
}
```
  
```{r example-merge_processed_spectra}
# Import example spectra and process spectra
directory_for_biotyper_spectra <- system.file("toy-species-spectra", package = "maldipickr")
spectra_list <- import_biotyper_spectra(directory_for_biotyper_spectra)
processed <- process_spectra(spectra_list)
# Merge the spectra to produce the feature matrix
fm <- merge_processed_spectra(list(processed))
dim(fm)
# Notice the difference when the interpolation is turned off
fm_no_interpolation <- merge_processed_spectra(list(processed), interpolate_missing = FALSE)
sum(fm == 0) # 0
sum(fm_no_interpolation == 0)
```
  
```{r tests-merge_processed_spectra}
directory_for_biotyper_spectra <- system.file("toy-species-spectra", package = "maldipickr")
spectra_list_test <- import_biotyper_spectra(directory_for_biotyper_spectra)[1:2]
processed_test <- process_spectra(spectra_list_test)
test_that("merge_processed_spectra works", {
  expect_equal(
    dim(merge_processed_spectra(list(processed_test))),
    c(2, 26)
  )
})
test_that("merge_processed_spectra fails with only empty peaks", {
  expect_error(
    list(
      createMassSpectrum(
        mass = 4500:5000,
        intensity = rep(0, 501),
        metaData = list(fullName = "foo")
      )
    ) %>% process_spectra() %>%
      list() %>% merge_processed_spectra(),
    "no list of MALDIquant::MassPeaks objects!"
  )
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_process_spectra.Rmd", vignette_name = "Dereplicate Bruker MALDI Biotyper spectra")
```
