---
title: "utils"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Is the well on the edges of the plate?



```{r function-is_well_on_edge}
#' Identify the wells on the plate's edge
#'
#'
#' @details
#' Flag the wells located on the edges of a 96- or 384-well plate, based on the following well numbering:
#'
#' * Well numbers start at 1
#' * Well are numbered from left to right and then top to bottom of the plate.
#'
#' @param well_number A vector of positive numeric well identifier
#' @param plate_layout An integer indicating the maximum number of well on the plate
#' @param edges A character vector pointing which plate edges should be considered
#' @param details A logical controlling whether a [data.frame] with more details should be returned
#'
#' @return A logical vector, the same length as `well_number` indicating whether the well is on the edge. If `details = TRUE`, the function returns a [data.frame] that complements the logical vector with the `well_number`, row and column positions.
#' @export
#'
#' @examples
is_well_on_edge <- function(
    well_number,
    plate_layout = c(96, 384),
    edges = c("top", "bottom", "left", "right"),
    details = FALSE) {
  if (!is.numeric(well_number)) {
    stop("The well number is not an numeric vector")
  }
  if (any(well_number <= 0)) {
    stop("The well number is not a positive only vector")
  }
  if (plate_layout != 96 & plate_layout != 384) {
    stop(
      "The expected plate layouts are 96 or 384 wells."
    )
  }
  if (any(max(well_number, plate_layout) > plate_layout)) {
    stop(
      "The well number vector has elements that exceeds the expected maximum",
      " well number for a plate layout of ", plate_layout, " wells."
    )
  }
  well_number <- as.integer(well_number)

  row_col_max <- c("row" = 8, "col" = 12)
  if (plate_layout == 384) {
    row_col_max <- 2 * row_col_max
  }

  # Convert well number to
  #   row identifier with the integer part of the division
  #     shifted by 1 (because 1-index in plates)
  #   col identifier with the modulo(remaining) of the division
  row_positions <- ((well_number - 1) %/% row_col_max["col"]) + 1 # modulo
  col_positions <- ((well_number - 1) %% row_col_max["col"]) + 1 # integer div

  mat <- cbind(row_positions, col_positions)
  colnames(mat) <- c("row", "col")
  # Being on the edge:
  #   top: row 1; all columns
  #   left: all rows; col 1
  #   bottom: last row; all columns
  #   right: all rows; last col

  edge_type <- list(
    "top" = apply(mat, 1, function(coord) {
      coord[1] == 1 & coord[2] <= row_col_max["col"]
    }),
    "bottom" = apply(mat, 1, function(coord) {
      coord[1] == row_col_max["row"] & coord[2] <= row_col_max["col"]
    }),
    "left" = apply(mat, 1, function(coord) {
      coord[1] <= row_col_max["row"] & coord[2] == 1
    }),
    "right" = apply(mat, 1, function(coord) {
      coord[1] <= row_col_max["row"] & coord[2] == row_col_max["col"]
    })
  )
  # Keep only the wanted edges and combine logical with OR
  edges <- match.arg(edges, several.ok = TRUE)
  edge_type <- edge_type[edges]
  is_edge <- Reduce(`|`, edge_type)

  if (isTRUE(details)) {
    return(data.frame(well_number, mat, is_edge, row.names = NULL))
  }
  return(unname(is_edge))
}
```

```{r examples-is_well_on_edge}
# Logical vector indicating whether the wells are on the four edges
is_well_on_edge(1:96, plate_layout = 96)
# More details can be obtained to verify the results
well_df <- is_well_on_edge(1:96, plate_layout = 96, details = TRUE)
# And the resulting prediction displayed
matrix(well_df$is_edge, ncol = max(well_df$col), byrow = TRUE)
```

```{r tests-is_well_on_edge}
test_that("is_well_on_edge works", {
  expect_equal(
    which(is_well_on_edge(1:96, plate_layout = 96)),
    c(1:13, 24, 25, 36, 37, 48, 49, 60, 61, 72, 73, 84:96)
  )
  expect_false(
    is_well_on_edge(23, plate_layout = 96)
  )
  expect_true(
    is_well_on_edge(23, plate_layout = 384)
  )
})
test_that("is_well_on_edge fails", {
  expect_error(
    is_well_on_edge(0), "The well number is not a positive only vector"
  )
  expect_error(
    is_well_on_edge(NA, plate_layout = 96),
    "The well number is not an numeric vector"
  )
  expect_error(
    is_well_on_edge(2, plate_layout = 84),
    "The expected plate layouts are 96 or 384 wells."
  )
})
```


# is_a_rds_list
    
```{r function-is_a_rds_list}
#' Check if the list provided is correctly a list of RDS paths
#'
#'
#' @return A logical TRUE if the list indicates paths of RDS files that exists. FALSE otherwise.
#'
#' @noRd
is_a_rds_list <- function(rds_list) {
  if (typeof(rds_list[[1]]) != "character") {
    stop(
      "The list does not contain characters"
    )
  }
  exts <- vapply(rds_list, tools::file_ext, FUN.VALUE = character(1)) %>% toupper()
  if (any(exts != "RDS")) {
    stop(
      "The list contains paths that do not end with the expected .RDS suffix."
    )
  }
  existences <- vapply(rds_list, file.exists, FUN.VALUE = logical(1))
  if (any(!existences)) {
    stop(
      "The list contains paths pointing to RDS files that do not exist."
    )
  }
  return(TRUE)
}
```
  
```{r example-is_a_rds_list}
is_a_rds_list(list("does-not-exists.RDS"))
```
  
```{r tests-is_a_rds_list}
tmp <- gsub("[: ]", "_", Sys.time())
file.create(paste0(tmp, ".RDS"))
test_that("is_a_rds_list works", {
  expect_true(
    is_a_rds_list(list(paste0(tmp, ".RDS")))
  )
})
file.remove(paste0(tmp, ".RDS"))
test_that("is_a_rds_list fails", {
  expect_error(
    is_a_rds_list(list(T)),
    "The list does not contain characters"
  )
  expect_error(
    is_a_rds_list(list("test.RDS", "foo.bar")),
    "The list contains paths that do not end with the expected .RDS suffix."
  )
  expect_error(
    is_a_rds_list(list("does-not-exists.RDS", "does-not-exists-also.RDS")),
    "The list contains paths pointing to RDS files that do not exist."
  )
})
```


# is_a_processed_spectra_list
    
```{r function-is_a_processed_spectra_list}
#' Check if the list provided is correctly a list of processed_spectra objects paths
#'
#'
#' @return A logical TRUE if the list contains objects created by [process_spectra]. FALSE otherwise.
#'
#' @noRd
is_a_processed_spectra_list <- function(process_spectra_list) {
  # List depth snippet from comment by https://stackoverflow.com/users/1201032/flodel
  # src: https://stackoverflow.com/a/13433689
  depth <- function(this) ifelse(is.list(this), 1L + max(vapply(this, depth, FUN.VALUE = integer(1))), 0L)

  if (depth(process_spectra_list) != 3) {
    if (depth(process_spectra_list) == 2) {
      stop(
        "The processed_spectra object is not a list of lists as expected, but close enough!\n",
        "Please wrap the provided object in list(processed_spectra)."
      )
    } else {
      stop(
        "The processed_spectra object is not a list of lists as expected!"
      )
    }
  }
  if (typeof(process_spectra_list[[1]]) != "list") {
    stop(
      "The list does not contain list objects ",
      "produced by `maldipickr::process_spectra()` as expected."
    )
  }
  object_names <- Map(base::names, process_spectra_list) %>%
    base::unique() %>%
    base::unlist()
  if (length(object_names) != 3 || any(object_names != c("spectra", "peaks", "metadata"))) {
    stop(
      "The list does not contain the three expected named objects ",
      "(spectra, peaks and metadata) produced by `maldipickr::process_spectra()`."
    )
  }
  if (base::class(process_spectra_list[[1]][["spectra"]][[1]]) != "MassSpectrum") {
    stop(
      "The 'spectra' list is not a MALDIquant::MassSpectrum object!"
    )
  }
  if (base::class(process_spectra_list[[1]][["peaks"]][[1]]) != "MassPeaks") {
    stop(
      "The 'spectra' list is not a MALDIquant::MassPeaks object!"
    )
  }
  if (any(base::class(process_spectra_list[[1]]$metadata) != c("tbl_df", "tbl", "data.frame"))) {
    stop(
      "The 'metadata' is not a tibble!"
    )
  }
  return(TRUE)
}
```
  
```{r example-is_a_processed_spectra_list}
foo <- list(
  "spectra" = list(MALDIquant::createMassSpectrum(1, 1)),
  "peaks" = list(MALDIquant::createMassPeaks(1, 1)),
  "metadata" = tibble::tibble(name = "foo")
)
is_a_processed_spectra_list(foo)
```
  
```{r tests-is_a_processed_spectra_list}
foo <- list(
  "spectra" = list(MALDIquant::createMassSpectrum(1, 1)),
  "peaks" = list(MALDIquant::createMassPeaks(1, 1)),
  "metadata" = tibble::tibble(name = "foo")
)
test_that("is_a_processed_spectra_list works", {
  expect_true(
    is_a_processed_spectra_list(list(foo))
  )
  expect_true(
    is_a_processed_spectra_list(list(foo, foo))
  )
})
test_that("is_a_processed_spectra_list fails", {
  expect_error(
    is_a_processed_spectra_list(list(TRUE)),
    "The processed_spectra object is not a list of lists as expected!"
  )
  expect_error(
    is_a_processed_spectra_list(foo),
    "The processed_spectra object is not a list of lists as expected, but close enough!"
  )
  expect_error(
    is_a_processed_spectra_list(list(list(list(TRUE)))),
    "The list does not contain the three expected named objects"
  )
  expect_error(
    is_a_processed_spectra_list(
      list(list(
        "spectra" = list(TRUE),
        "peaks" = list(MALDIquant::createMassPeaks(1, 1)),
        "metadata" = tibble::tibble(name = "foo")
      ))
    ),
    "The 'spectra' list is not a MALDIquant::MassSpectrum object!"
  )
  expect_error(
    is_a_processed_spectra_list(
      list(list(
        "spectra" = list(MALDIquant::createMassSpectrum(1, 1)),
        "peaks" = list(TRUE),
        "metadata" = tibble::tibble(name = "foo")
      ))
    ),
    "The 'spectra' list is not a MALDIquant::MassPeaks object!"
  )
  expect_error(
    is_a_processed_spectra_list(
      list(list(
        "spectra" = list(MALDIquant::createMassSpectrum(1, 1)),
        "peaks" = list(MALDIquant::createMassPeaks(1, 1)),
        "metadata" = TRUE
      )),
      "not a tibble"
    )
  )
})
```
  
# get_spectra_names
    
```{r function-get_spectra_names}
#' Extract spectra names and check for uniqueness
#' 
#' Given the list of raw spectra, `get_spectra_names()` extracts the spectra names
#' using the file metadata, and warns if the associated sanitized names are not unique.
#' 
#' @param spectra_list A list of [MALDIquant::MassSpectrum] objects.
#' 
#' @return A tibble with four columns
#' * `sanitized_name`: spectra names based on `fullName` where dots and dashes are converted to underscores
#' * `name`: spectra name using the `name` label in the spectra metadata
#' * `fullName`: spectra full name using the `fullName` label in the spectra metadata
#' * `file`: the path to the raw spectra data
#' 
#' @export
get_spectra_names <- function(spectra_list){
    object_class <- vapply(spectra_list, base::class, FUN.VALUE = character(1)) %>%
      base::unique()
    if(object_class != "MassSpectrum"){
      stop(
        "The 'spectra_list' is not a list of MALDIquant::MassSpectrum objects!"
      )
    }
    
    # Need to make sure that the spectra are not empty here to avoid
    # a tibble issue like:
    # Error in `tibble::as_tibble_row()`:
    # ! Columns 1, 2, and 3 must be named.
    #
    # Therefore, error if the spectra is empty or not
    empty_spectra <- vapply(spectra_list, MALDIquant::isEmpty, FUN.VALUE = logical(1))
    
    if(any(empty_spectra)){
      stop(
        "Empty spectra detected! Preprocess the data accordingly using `check_spectra()`"
      )
    }
    
    spectra_names <- lapply(spectra_list,  function(spectra){
      MALDIquant::metaData(spectra)[c("name", "fullName", "file")] %>%
        tibble::as_tibble_row()
    }) %>%
      dplyr::bind_rows() %>%
      dplyr::mutate(
        "sanitized_name" = gsub("[-\\.]", "_",.data$fullName)
      ) %>% 
      dplyr::relocate("sanitized_name")
    
    if( nrow(spectra_names) > dplyr::n_distinct(spectra_names[["sanitized_name"]])){
      warning(
        "Non-unique values in spectra names!",
        "\n\nQuickfix: use `dplyr::mutate(sanitized_name = base::make.unique(sanitized_name))`"
      )
    }
      return(spectra_names)
}
```
  
```{r example-get_spectra_names}
# Get an example directory of six Bruker MALDI Biotyper spectra
directory_biotyper_spectra <- system.file(
  "toy-species-spectra",
  package = "maldipickr"
)
# Import the six spectra
spectra_list <- import_biotyper_spectra(directory_biotyper_spectra)
# Extract the names
get_spectra_names(spectra_list)

# Artificially create duplicated entries to show the warning
get_spectra_names(spectra_list[c(1,1)])
```
  
```{r tests-get_spectra_names}
directory_biotyper_spectra <- system.file("toy-species-spectra", package = "maldipickr")
spectra_list_test <- import_biotyper_spectra(directory_biotyper_spectra)[1:2]
test_that("get_spectra_names works", {
  expect_no_warning(
    out <- get_spectra_names(spectra_list_test)
  )
  expect_equal(
    dim(out), c(2, 4)
  )
  expect_equal(
    out$sanitized_name, c("species1_G2", "species2_E11")
  )
})
test_that("get_spectra_names warns when duplicate", {
  expect_warning(
    out <- get_spectra_names(spectra_list_test[c(1,1)]),
    "Non-unique values in spectra names!"
  )
  expect_equal(
    dim(out), c(2, 4)
  )
  expect_equal(
    out$sanitized_name, c("species1_G2", "species1_G2")
  )
})
test_that("get_spectra_names fails on empty spectra", {
  expect_error(
    get_spectra_names(c(MALDIquant::createMassSpectrum(0, 0))),
    "Empty spectra detected!"
  )
})
```


# Remove (raw or processed) spectra

## Internal remove_spectra_logical for raw spectra

```{r function-remove_spectra_logical}
#' Remove raw spectra
#'
#' The `remove_spectra()` function is used to discard specific spectra from raw spectra list by removing them.
#'
#' @param spectra_list A list of [MALDIquant::MassSpectrum] objects
#' @param to_remove The spectra to be removed. A logical vector same size of `spectra_list` or from [check_spectra] function
#'
#' @return The same object as `spectra_list` minus the spectra in `to_remove`.
#' @noRd
remove_spectra_logical <- function(spectra_list, to_remove) {
  to_remove_class <- base::unlist(to_remove) %>% base::class()
  if (to_remove_class != "logical") {
    stop(
      "Non logical values in 'to_remove' against expectations\n",
      "You could provide the output of `check_spectra()`."
    )
  }
  to_remove <- switch(base::class(to_remove),
    "list" = Reduce(`|`, to_remove),
    "logical" = to_remove
  )
  if (base::length(spectra_list) != base::length(to_remove)) {
    stop(
      "Unequal lengths between spectra_list and to_remove"
    )
  }
  return(spectra_list[!to_remove])
}
```

```{r tests-remove_spectra_logical}
half_empty <- c(
  MALDIquant::createMassSpectrum(1:3, c(0,0,0)),
  MALDIquant::createMassSpectrum(11:13, 11:13)
)
test_that("remove_spectra_logical works", {
  expect_length(
    remove_spectra_logical(half_empty, check_spectra(half_empty)),
    1
  )
  expect_length(
    remove_spectra_logical(half_empty, to_remove = c(TRUE, FALSE)),
    1
  )
})
test_that("remove_spectra_logical fails with wrong input", {
  expect_error(
    remove_spectra_logical(half_empty, to_remove = "please_remove"),
    "Non logical values"
  )
  expect_error(
    remove_spectra_logical(half_empty, to_remove = TRUE),
    "Unequal lengths"
  )
})
```
  
## Exported function to remove spectra

```{r function-remove_spectra}
#' Remove (raw or processed) spectra
#'
#' The `remove_spectra()` function is used to discard specific spectra from (1) raw spectra list by removing them, or (2) processed spectra by removing them from the spectra, peaks and metadata objects.
#'
#' @param spectra_list A list of [MALDIquant::MassSpectrum] objects OR A list of processed spectra from [process_spectra]
#' @param to_remove The spectra to be removed. In the case of raw spectra: a logical vector same size of `spectra_list` or from [check_spectra] function. In the case of processed spectra: names of the spectra as formatted in [get_spectra_names] in the `sanitized_name` column.
#'
#' @return The same object as `spectra_list` minus the spectra in `to_remove`.
#'
#' @export
remove_spectra <- function(spectra_list, to_remove) {
  if (base::class(spectra_list) == "list" &
    base::class(spectra_list[[1]]) == "MassSpectrum"
  ) {
    # spectra_list is a raw spectra
    # to_remove should be logical vector
    remove_spectra_logical(spectra_list, to_remove) %>%
      return()
  } else if (is_a_processed_spectra_list(spectra_list)) {
    if (base::class(to_remove) != "character") {
      stop(
        "remove_spectra() with processed spectra expects spectra names in 'to_remove'"
      )
    }
    spectra_names <- spectra_list[[1]][["metadata"]][["name"]]
    if (!to_remove %in% spectra_names) {
      stop(
        "Spectra names in 'to_remove' are not present in the spectra list"
      )
    }
    to_remove <- spectra_names %in% to_remove

    list(
      "spectra" = remove_spectra_logical(spectra_list[[1]][["spectra"]], to_remove),
      "peaks" = remove_spectra_logical(spectra_list[[1]][["peaks"]], to_remove),
      "metadata" = spectra_list[[1]][["metadata"]][!to_remove, ]
    ) %>% return()
  } else {
    stop("spectra_list is not a list of raw spectra nor a list of processed spectra")
  }
}
```

```{r examples-remove_spectra}
# Get an example directory of six Bruker MALDI Biotyper spectra
directory_biotyper_spectra <- system.file(
  "toy-species-spectra",
  package = "maldipickr"
)
# Import only the first two spectra
spectra_list <- import_biotyper_spectra(directory_biotyper_spectra)[1:2]
# Introduce artificially an empty raw spectra
spectra_list <- c(spectra_list, MALDIquant::createMassSpectrum(0, 0))
# Empty spectra are detected by `check_spectra()`
#   and can be removed by `remove_spectra()`
spectra_list %>% 
  remove_spectra(to_remove = check_spectra(.))

# Get an example processed spectra
processed_path <- system.file(
    "three_processed_spectra_with_one_peakless.RDS",
    package = "maldipickr")
processed <- readRDS(processed_path) %>% list()

# Remove a specific spectra
remove_spectra(processed, "empty_H12")
```

```{r tests-remove_spectra}
# Processed data
processed_path <- system.file(
    "three_processed_spectra_with_one_peakless.RDS",
    package = "maldipickr")
processed <- readRDS(processed_path) %>% list()
test_that("remove_spectra works on processed spectra", {
  expect_mapequal(
    remove_spectra(processed, "empty_H12") %>% base::lengths(),
    c(spectra = 2L, peaks = 2L, metadata = 3L)
  )
})
test_that("remove_spectra fails with wrong input on processed spectra", {
  expect_error(
    remove_spectra(processed, "empty_H2") ,
    "Spectra names in 'to_remove'"
  )
  expect_error(
    remove_spectra(processed, c(TRUE, FALSE)) ,
    "remove_spectra\\(\\) with processed spectra expects spectra names"
  )
})
# Raw data
directory_biotyper_spectra <- system.file(
  "toy-species-spectra",
  package = "maldipickr"
)
spectra_list <- import_biotyper_spectra(directory_biotyper_spectra)[1:2]
spectra_list <- c(spectra_list, MALDIquant::createMassSpectrum(0, 0))
test_that("remove_spectra works on raw spectra", {
  expect_equal(
    remove_spectra(spectra_list, c(FALSE, FALSE, TRUE)) %>% base::lengths(),
    c(20882L, 20882L)
  )
  expect_equal(
    remove_spectra(spectra_list, check_spectra(spectra_list)) %>% base::lengths(),
    c(20882L, 20882L)
  )
})
test_that("remove_spectra fails with wrong input on raw spectra", {
  expect_error(
    remove_spectra(spectra_list, "species1"),
    "Non logical values in 'to_remove'"
  )
})
```



```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_utils.Rmd", vignette_name = NA)
```
