# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

dummy_multiple_paths <- system.file(
  c("biotyper.csv","biotyper_empty.csv", "biotyper.csv"),
  package = "maldipickr")
test_that("read_many_biotyper_reports works", {
  expect_equal(
    nrow(
      read_many_biotyper_reports(
        dummy_multiple_paths,
        report_ids = c("first","second","third")
      )
    ), 6
  )
})
test_that("read_many_biotyper_reports works with arguments passed to mutate", {
  expect_equal(
    read_many_biotyper_reports(
      dummy_multiple_paths,
      report_ids = c("first","second","third"),
      growth_temperature = 37.0
    ) %>%
      dplyr::pull(growth_temperature) %>% unique(), 37 
  )
})
