# WARNING - Generated by {fusen} from dev/dereplicate-spectra.Rmd: do not edit by hand

clusters <- readRDS(system.file("clusters_tibble.RDS", package = "maldipickr"))
set.seed(104)
metadata <- dplyr::transmute(clusters, name = name, OD600 = runif(n = nrow(clusters)))
test_that("pick_spectra works", {
  expect_true(
    identical(
      pick_spectra(clusters)$is_reference,
      pick_spectra(clusters)$to_pick
    )
  )
  expect_output(
    pick_spectra(clusters, discard_regex = "E11", only_show_discarded = TRUE),
    "species2_E11 species2_E12"
  )
  expect_equal(
    pick_spectra(clusters, metadata, "OD600")$to_pick,
    c(FALSE, TRUE, FALSE, TRUE, FALSE, FALSE)
  )
  expect_equal(
    pick_spectra(clusters, is_sorted = TRUE)$to_pick,
    c(FALSE, FALSE, TRUE, FALSE, TRUE, FALSE)
  )
})
test_that("pick_spectra fails without metadata and column", {
  expect_error(
    pick_spectra(clusters[, -1]),
    "lacks one of the following columns"
  )
  expect_error(
    pick_spectra(clusters[, -6]),
    "No additional metadata are provided"
  )
  expect_error(
    pick_spectra(clusters, only_show_discarded = TRUE),
    "No regex to discard clusters were provided"
  )
  expect_error(
    pick_spectra(clusters, metadata),
    "Additional metadata"
  )
})
