# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

# test_that("my_median works properly and show error if needed", {
#   expect_true(my_median(1:12) == 6.5)
#   expect_error(my_median("text"))
# })
# Test with a correct and empty datasets in "inst/"
biotyper <- system.file("biotyper.csv", package = "maldipickr")
biotyper_empty <- system.file("biotyper_empty.csv", package = "maldipickr")

# Apply test on my function
test_that("read_biotyper_report works properly with correct dataset and best hits", {
  expect_equal(
    nrow(read_biotyper_report(biotyper)), 3
  )
  expect_equal(
    ncol(read_biotyper_report(biotyper)), 7
  )
  expect_equal(
    dplyr::pull(read_biotyper_report(biotyper), bruker_species),
    c("not reliable identification", "Escherichia coli", "Kosakonia cowanii")
  )
})
test_that("read_biotyper_report works properly with correct dataset and all hits", {
  expect_equal(
    nrow(read_biotyper_report(biotyper, best_hits = FALSE)), 3
  )
  expect_equal(
    ncol(read_biotyper_report(biotyper, best_hits = FALSE)), 52
  )
})
test_that("read_biotyper_report is empty when no peaks are found", {
  expect_equal(
    nrow(read_biotyper_report(biotyper_empty)), 0
  )
  expect_warning(
    read_biotyper_report(biotyper_empty), "Remove"
  )
})
