# WARNING - Generated by {fusen} from dev/maldipickr-workflow-with-targets.Rmd: do not edit by hand

test_that("tar_pick_with_similarity works", {
  expect_true(inherits(tar_pick_with_similarity, "function")) 
})
