# WARNING - Generated by {fusen} from dev/import-data.Rmd: do not edit by hand

test_that("check_spectra works", {
  expect_type(
    check_spectra(
      c(MALDIquant::createMassSpectrum(1:3, 1:3), MALDIquant::createMassSpectrum(11:13, 11:13))
    ), "list"
  )
})
test_that("check_spectra warns with empty spectra", {
  expect_warning(
    check_spectra(c(MALDIquant::createMassSpectrum(mass = 0, intensity = 0))),
    "Some spectra"
  )
})
