# WARNING - Generated by {fusen} from dev/import-data.Rmd: do not edit by hand

directory_biotyper_spectra <- system.file("toy-species-spectra", package = "maldipickr")
directory_biotyper_spectra_with_acqus <- system.file("with-acqus", package = "maldipickr")
test_that("import_biotyper_spectra works", {
  expect_no_error(
    spectra_list <- import_biotyper_spectra(directory_biotyper_spectra)
  )
  expect_length(
    spectra_list, 6
  )
  expect_type(
    spectra_list, "list"
  )
})
test_that("import_biotyper_spectra works with symlinks",{
  expect_no_error(
    spectra_with_acqus <- import_biotyper_spectra(directory_biotyper_spectra_with_acqus)
  )
  expect_length(
    spectra_with_acqus, 1
  )
  expect_type(
    spectra_with_acqus, "list"
  )
})
test_that("import_biotyper_spectra fails", {
  expect_error(
    import_biotyper_spectra(
      paste0(directory_biotyper_spectra, "/0_G2/1/1SLin/acqu")
    ), "Directory"
  )
})
