# WARNING - Generated by {fusen} from dev/import-data.Rmd: do not edit by hand

directory_for_biotyper_spectra <- system.file("toy-species-spectra", package = "maldipickr")
spectra_list <- import_biotyper_spectra(directory_for_biotyper_spectra)
test_that("import_biotyper_spectra works", {
  expect_length(
    spectra_list, 6
  )
  expect_type(
    spectra_list, "list"
  )
})
test_that("import_biotyper_spectra fails", {
  expect_error(
    import_biotyper_spectra(
      paste0(directory_for_biotyper_spectra, "/0_G2/1/1SLin/acqu")
    ), "Directory"
  )
})
