# WARNING - Generated by {fusen} from dev/flat_process_spectra.Rmd: do not edit by hand

directory_for_biotyper_spectra <- system.file("toy-species-spectra", package = "maldipickr")
spectra_list_test <- import_biotyper_spectra(directory_for_biotyper_spectra)[1:2]
test_that("process_spectra works", {
  expect_equal(
    process_spectra(spectra_list_test)$metadata,
    structure(
      list(
        SNR = c(5.08959045014141, 5.54373537030499),
        peaks = c(21, 22)
      ),
      class = "data.frame",
      row.names = c("species1_G2", "species2_E11")
    )
  )
})
test_that("process_spectra warns on empty spectra", {
  expect_warning(
    process_spectra(c(MALDIquant::createMassSpectrum(0, 0))),
    "MassSpectrum object is empty"
  )
})
