# WARNING - Generated by {fusen} from dev/maldipickr-workflow-with-targets.Rmd: do not edit by hand

test_that("tar_import_and_process_spectra works", {
  expect_true(inherits(tar_import_and_process_spectra, "function")) 
})
