# WARNING - Generated by {fusen} from dev/import-data.Rmd: do not edit by hand

directory_for_biotyper_spectra <- system.file("toy-species-spectra", package = "maldipickr")
test_that("import_biotyper_spectra works", {
  expect_length(
    import_biotyper_spectra(directory_for_biotyper_spectra),
    6
  )
})
