# WARNING - Generated by {fusen} from dev/dereplicate-spectra.Rmd: do not edit by hand

test_that("import_spede_clusters works", {
  expect_equal(
    nrow(import_spede_clusters(
      system.file("spede.csv", package = "maldipickr")
    )), 6
  )
})
test_that("import_spede_clusters is empty when no spectra where matched", {
  expect_equal(
    nrow(import_spede_clusters(
      system.file("spede-empty.csv", package = "maldipickr")
    )), 0
  )
})
