# WARNING - Generated by {fusen} from dev/import-data.Rmd: do not edit by hand

#' Importing a list of Bruker MALDI Biotyper CSV reports
#'
#' @param path_to_reports A vector of paths to the csv files to be imported by [read_biotyper_report()].
#' @param report_ids A vector of character names for each of the reports.
#' @param best_hits A logical indicating whether to return only the best hit in the [read_biotyper_report()] function.
#' @param ... Name-value pairs to be passed on to [dplyr::mutate()]
#'
#' @return A tibble just like the [read_biotyper_report()] function except for an additional column `name` with the `report_ids` used as a prefix of the `spot` name.
#'
#' @seealso [read_biotyper_report]
#'
#' @note The report identifiers are sanitised to convert all dashes (`-`) as underscores (`_`).
#'
#' @export
#'
#' @examples
#' # List of Bruker MALDI Biotyper reports
#' reports_paths <- system.file(
#'   c("biotyper.csv", "biotyper.csv", "biotyper.csv"),
#'   package = "maldipickr"
#' )
#' # Read the list of reports and combine them in a single tibble
#' read_many_biotyper_reports(
#'   reports_paths,
#'   report_ids = c("first", "second", "third"),
#'   # Additional metadata below are passed to dplyr::mutate
#'   growth_temperature = 37.0
#' )
read_many_biotyper_reports <- function(path_to_reports, report_ids, best_hits = TRUE, ...) {
  # Import the Bruker Biotyper reports as a named list
  breports <- lapply(
    path_to_reports,
    read_biotyper_report,
    best_hits
  )
  names(breports) <- report_ids
  # Conversion of a named list of dataframe to the dataframe with the name as
  #  a column is now super easy with enframe()
  tibble::enframe(breports) %>%
    tidyr::unnest("value") %>%
    dplyr::mutate(
      "name" = paste(gsub("-", "_", .data$name), .data$spot, sep = "_"),
      "bruker_species" = if_else(
        .data$bruker_species == "not reliable identification",
        paste(.data$bruker_species, .data$name), # make the unmatched species unique for later counts
        .data$bruker_species
      ),
      ...
    ) %>%
    return()
}
