# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Importing Bruker MALDI Biotyper CSV report
#'
#'
#' The headerless table exported by the Compass software in the Bruker MALDI
#' Biotyper device is separated by semi-colons and has empty columns which prevent
#' an easy import by R. This function reads the report correctly as a tibble.
#' 
#' @details
#' The headerless table contains identification information for each target processed by
#' the Biotyper device:
#' * `bruker_quality`: a character encoding the quality of the identification with potentially multiple "+" symbol or only one "-"
#' * `bruker_species`: the species name associated with the MALDI spectrum analyzed.
#' * `bruker_taxid`: the NCBI Taxonomy Identifier of the species name in the column species
#' * `bruker_hash`: a hash from an undocumented checksum function probably to encode the database entry.
#' * `bruker_log`: the log-score of the identification.
#' 
#' @param path Path to the semi-colon separated table
#' @param best_hits A logical indicating whether to return only the best hit
#'
#' @return
#' A tibble (see Details for the columns description)
#' @export
#'
#' @examples
#' # Example with your dataset in "inst/"
#' biotyper <- system.file("biotyper.csv", package = "maldipickr")
#' read_biotyper_report(biotyper)
read_biotyper_report <- function(path, best_hits = TRUE){
  require(tidyr)
  require(dplyr)
  require(tibble)
  # Prepare the columns names, because 10 hits are reported by default
  prep_names <- tidyr::expand_grid(
    prefix = "bruker",
    iteration = sprintf("%02d", 1:10), # Because 10 hits per spot with each 5 columns
    variables = c("quality", "species", "taxid", "hash", "log")
  ) %>% dplyr::mutate(
    type = if_else( variables == "log", "d", "c"),
    col_names = paste(prefix, iteration, variables, sep = "_")
  )
  
  # Read in the report, usually warnings about problems and
  #  inconsistent number of columns are triggered
  breport <- read.delim(
    path, 
    col.names = c("spot", "sample_name", pull(prep_names, col_names)),
    sep = ";", header = FALSE,
    na = c("NA", "E1", "E2", "") # Added E1 identification in taxid as NA
  )
  no_peak_lgl <- breport$bruker_01_species == "no peaks found"
  
  # Remove the spot for which no peaks were detected, and warn the user
  breport <- tibble::as_tibble(breport) %>%
    dplyr::filter(bruker_01_species != "no peaks found")
  if(sum(no_peak_lgl) > 0 ){
    warning(
      sum(no_peak_lgl), " rows out of ", length(no_peak_lgl),
      " due to no peaks found")    
  }

  if(best_hits){
    breport %>%
      select(spot, sample_name, starts_with("bruker_01")) %>%
      rename_with(~ gsub("_01", "", .x)) %>%
      return()
  } else{
    return(breport)
  }
}
