# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Importing Bruker MALDI Biotyper CSV report
#'
#'
#' The headerless table exported by the Compass software in the Bruker MALDI
#' Biotyper device is separated by semi-colons and has empty columns which prevent
#' an easy import in R. This function reads the report correctly as a tibble.
#' 
#' @details
#' The headerless table contains identification information for each target processed by
#' the Biotyper device and once processed by the `read_biotyper_report`,
#' the following seven columns are available in the tibble, _when using the `best_hits = TRUE` option:
#' * `spot`: an integer indicating the spot number of the MALDI target (i.e., plate)
#' * `sample_name`: the character string provided during the preparation of the MALDI target (i.e., plate)
#' * `bruker_quality`: a character encoding the quality of the identification with potentially multiple "+" symbol or only one "-"
#' * `bruker_species`: the species name associated with the MALDI spectrum analyzed.
#' * `bruker_taxid`: the NCBI Taxonomy Identifier of the species name in the column species
#' * `bruker_hash`: a hash from an undocumented checksum function probably to encode the database entry.
#' * `bruker_log`: the log-score of the identification.
#' 
#' When all hits are returned (with `best_hits = FALSE`), the two columns `spot` and `sample_name`
#' remains unchanged, but the five columns prefixed by `bruker_` contains the hit number:
#'
#' * `bruker_01_quality`
#' * `bruker_01_species`
#' * `bruker_01_taxid`
#' * `bruker_01_hash`
#' * `bruker_01_log`
#' * `bruker_02_quality`
#' * ...
#' * `bruker_10_species`
#' * `bruker_10_taxid`
#' * `bruker_10_hash`
#' * `bruker_10_log`
#'
#' @param path Path to the semi-colon separated table
#' @param best_hits A logical indicating whether to return only the best hit
#'
#' @return
#' A tibble of 7 columns (`best_hits = TRUE`) or 52 columns (`best_hits = FALSE`). See Details for the description of the columns.
#' @export
#'
#' @examples
#' # Get a example Bruker report
#' biotyper <- system.file("biotyper.csv", package = "maldipickr")
#' # Import the report as a tibble
#' report_tibble <- read_biotyper_report(biotyper)
#' # Display the tibble
#' report_tibble
read_biotyper_report <- function(path, best_hits = TRUE){
  # Prepare the columns names, because 10 hits are reported by default
  prep_names <- tidyr::expand_grid(
    prefix = "bruker",
    iteration = sprintf("%02d", 1:10), # Because 10 hits per spot with each 5 columns
    variables = c("quality", "species", "taxid", "hash", "log")
  ) %>% dplyr::mutate(
    type = dplyr::if_else( variables == "log", "d", "c"),
    col_names = paste(prefix, iteration, variables, sep = "_")
  )
  
  # Read in the report, usually warnings about problems and
  #  inconsistent number of columns are triggered
  breport <- utils::read.delim(
    path, 
    col.names = c("spot", "sample_name", pull(prep_names, col_names)),
    sep = ";", header = FALSE,
    na = c("NA", "E1", "E2", "") # Added E1 identification in taxid as NA
  )
  no_peak_lgl <- breport$bruker_01_species == "no peaks found"
  
  # Remove the spot for which no peaks were detected, and warn the user
  breport <- tibble::as_tibble(breport) %>%
    dplyr::filter(bruker_01_species != "no peaks found")
  if(sum(no_peak_lgl) > 0 ){
    warning(
      "Remove ", sum(no_peak_lgl), " row(s) out of ", length(no_peak_lgl),
      " due to no peaks found")    
  }

  if(best_hits){
    breport %>%
      dplyr::select(spot, sample_name, starts_with("bruker_01")) %>%
      dplyr::rename_with(~ gsub("_01", "", .x)) %>%
      return()
  } else{
    return(breport)
  }
}
