# WARNING - Generated by {fusen} from dev/maldipickr-workflow-with-targets.Rmd: do not edit by hand

#' Delineate clusters of spectra to be picked using targets
#' 
#' Description
#' 
#' @param name A symbol indicating the prefix of all targets created by the factory.
#' For instance, calling `tar_pick_with_similarity(anaerobe, ...)` will create
#'  the target `anaerobe_sim_interpolated` among others (see the Value section).
#' @param targets_spectra A list of targets produced by [tar_import_and_process_spectra] that should contains one or more targets named `*_processed`.
#' @param threshold A numeric value indicating the minimal cosine similarity between two spectra.
#' @param ... Arguments passed to [pick_spectra]
#'
#' @return A list of target objects whose names use the `name` argument as a prefix:
#' * `*_fm_interpolated` (e.g.,  `anaerobe_fm_interpolated`): a matrix produced by [merge_processed_spectra].
#' * `*_sim_interpolated` (e.g.,  `anaerobe_sim_interpolated`): a symetric cosine similarity matrix produced by [coop::tcosine].
#' 
#' @export
#' @examples
#' tar_pick_with_similarity()
tar_pick_with_similarity <- function(
    name,
    targets_spectra,
    threshold, ...) {
  rlang::check_installed(c("targets", "tarchetypes", "coop"),
    reason = "to facilitate {maldipickr} workflow development"
  )
  name <- targets::tar_deparse_language(substitute(name))
  targets::tar_assert_dbl(threshold)
  targets::tar_assert_list(targets_spectra)
  targets_spectra <- unlist(list(targets_spectra), recursive = TRUE)


  # It was tricky to apply the symbol transformation to a list whilst constructing
  #  a list structure that could be used correctly by merge_processed_spectra()
  # Thankfully, @wlandau suggested an awesome solution to a similar problem
  # https://github.com/ropensci/targets/discussions/461#discussioncomment-709984
  #
  # which will create list(fast_processed, slow_processed) from
  #  targets_spectra = c(fast_target_factory, slow_target_factory)
  name_processed <- tarchetypes::tar_select_names(targets_spectra, targets::ends_with("_processed"))
  processed_expr <- as.call(c(as.symbol("list"), lapply(name_processed, as.symbol)))


  name_fm <- paste0(name, "_fm_interpolated")
  name_sim <- paste0(name, "_sim_interpolated")


  sym_fm <- as.symbol(name_fm)
  sym_sim <- as.symbol(name_sim)
  list(
    targets::tar_target_raw(
      name = name_fm,
      command = substitute(merge_processed_spectra(processed_spectra),
        env = list(processed_spectra = processed_expr)
      )
    ),
    targets::tar_target_raw(
      name = name_sim,
      command = substitute(coop::tcosine(fm_interpolated),
        env = list(fm_interpolated = sym_fm)
      )
    )
  )
}
