# WARNING - Generated by {fusen} from dev/maldipickr-workflow-with-targets.Rmd: do not edit by hand

#' Import and process checked spectra using targets
#' 
#' 
#' Given a vector of paths to `acqus` and `acqu` MALDI Biotyper directories, this targets
#'  factory facilitates the steps from raw spectra to quality-checked processed spectra.
#' 
#' @param name A character indicating the prefix of all targets created by the factory.
#' For instance, `name = anaerobe` will create the target `anaerobe_spectra_raw` among others.
#' @param raw_spectra_directories A vector of paths to directories containing MALDI Biotyper spectra files. This is similar to the `biotyper_directory` parameter from [import_biotyper_spectra], but as a character vector.
#' @inheritParams check_spectra
#' @inheritParams targets::tar_target_raw
#'
#' @return A target object
#' 
#' @export
#' @examples
#' if (Sys.getenv("TAR_LONG_EXAMPLES") == "true") {
#'   targets::tar_dir({ # tar_dir() runs code from a temporary directory.
#'     targets::tar_script({
#'         library(maldipickr)
#'         list(
#'           tar_spectra_import(
#'             name = "example",
#'             raw_spectra_directories = system.file(
#'               "toy-species-spectra",
#'               package = "maldipickr"),
#'             tolerance = 1
#'           )
#'         )},ask = FALSE)
#'     targets::tar_make()
#'   })
#' }
tar_import_and_process_spectra <- function(
    name,
    raw_spectra_directories,
    tolerance,
    format = targets::tar_option_get("format")) {
  rlang::check_installed(c("targets", "tarchetypes"),
    reason = "to facilitate {maldipickr} workflow development"
  )
  targets::tar_assert_chr(name)
  targets::tar_assert_path(raw_spectra_directories)
  targets::tar_assert_dbl(tolerance)

  name_plates <- paste0(name, "_plates")
  name_spectra_raw <- paste0(name, "_spectra_raw")
  name_checks <- paste0(name, "_checks")
  name_spectra_stats <- paste0(name, "_spectra_stats")
  name_valid_spectra <- paste0(name, "_valid_spectra")
  name_processed <- paste0(name, "_processed")

  sym_plates <- as.symbol(name_plates)
  sym_spectra_raw <- as.symbol(name_spectra_raw)
  sym_checks <- as.symbol(name_checks)
  sym_spectra_stats <- as.symbol(name_spectra_stats)
  sym_valid_spectra <- as.symbol(name_valid_spectra)

  list(
    tarchetypes::tar_files_input_raw(name_plates,
      raw_spectra_directories,
      format = "file"
    ),
    targets::tar_target_raw(name_spectra_raw,
      command = substitute(suppressWarnings(import_biotyper_spectra(sym_plates)),
        env = list(sym_plates = sym_plates)
      ),
      pattern = substitute(map(sym_plates),
        env = list(sym_plates = sym_plates)
      ),
      format = format
    ),
    targets::tar_target_raw(name_checks,
      command = substitute(check_spectra(sym_spectra_raw, tolerance),
        env = list(tolerance = tolerance, sym_spectra_raw = sym_spectra_raw)
      ),
      pattern = substitute(map(sym_spectra_raw), env = list(sym_spectra_raw = sym_spectra_raw)),
      format = format
    ),
    targets::tar_target_raw(name_spectra_stats,
      command = substitute(
        gather_spectra_stats(sym_checks) %>%
          dplyr::mutate(maldi_plate = sym_plates),
        env = list(sym_checks = sym_checks, sym_plates = sym_plates)
      ),
      pattern = substitute(map(sym_checks, sym_plates),
        env = list(sym_checks = sym_checks, sym_plates = sym_plates)
      ),
      iteration = "vector", format = format
    ),
    # Filter-out non empty spectra and unusual spectra
    targets::tar_target_raw(name_valid_spectra,
      command = substitute(remove_spectra(sym_spectra_raw, sym_checks),
        env = list(sym_spectra_raw = sym_spectra_raw, sym_checks = sym_checks)
      ),
      pattern = substitute(map(sym_spectra_raw, sym_checks),
        env = list(sym_spectra_raw = sym_spectra_raw, sym_checks = sym_checks)
      ),
      format = format
    ),
    targets::tar_target_raw(name_processed,
      command = substitute(process_spectra(sym_valid_spectra),
        env = list(sym_valid_spectra = sym_valid_spectra)
      ),
      pattern = substitute(map(sym_valid_spectra),
        env = list(sym_valid_spectra = sym_valid_spectra)
      ),
      format = format
    )
  )
}
