# WARNING - Generated by {fusen} from dev/maldipickr-workflow-with-targets.Rmd: do not edit by hand

#' Delineate clusters of spectra to be picked using targets
#' 
#' Given upstream targets of processed spectra (from [tar_import_and_process_spectra])
#'  this target factory facilitates the steps from quality-checked
#'  processed spectra to clusters of spectra. See [targets::tar_target] for more
#'  information about what are target objects.
#' 
#' @param name A symbol indicating the prefix of all targets created by the factory.
#' For instance, calling `tar_pick_with_similarity(anaerobe, ...)` will create
#'  the target `anaerobe_sim_interpolated` among others (see the Value section).
#' @param targets_spectra A list of targets produced by [tar_import_and_process_spectra] that should contains one or more targets named `*_processed`.
#' @param threshold A numeric value indicating the minimal cosine similarity between two spectra.
#' @inheritParams pick_spectra
#'
#' @return A list of target objects whose names use the `name` argument as a prefix:
#' * `*_fm_interpolated` (e.g.,  `anaerobe_fm_interpolated`): a matrix produced by [merge_processed_spectra].
#' * `*_sim_interpolated` (e.g.,  `anaerobe_sim_interpolated`): a symmetric cosine similarity matrix produced by the transposed version of [coop::cosine].
#' * `*_df_interpolated` (e.g.,  `anaerobe_df_interpolated`): a tibble with the membership (i.e., which cluster label) each spectra belongs to produced by [delineate_with_similarity].
#' * `*_processed_metadata` (e.g.,  `anaerobe_processed_metadata`): a tibble of aggregated technical metadata for each spectra.
#' * `*_clusters` (e.g.,  `anaerobe_clusters`): a tibble indicating with the previous metadata and which spectra was chosen as reference produced by [set_reference_spectra].
#' * `*_picked` (e.g.,  `anaerobe_picked`): a tibble containing all the previous metadata but more importantly which spectra should be picked produced by [pick_spectra].
#' 
#' @export
#' @examples
#'\dontrun{tar_pick_with_similarity()}
tar_pick_with_similarity <- function(
    name,
    targets_spectra,
    threshold,
    metadata_df = NULL, criteria_column = NULL,
    hard_mask_column = NULL, soft_mask_column = NULL,
    is_descending_order = TRUE,
    is_sorted = FALSE) {
  rlang::check_installed(c("targets", "tarchetypes", "coop"),
    reason = "to facilitate {maldipickr} workflow development"
  )
  name <- targets::tar_deparse_language(substitute(name))
  targets::tar_assert_dbl(threshold)
  targets::tar_assert_list(targets_spectra)
  targets_spectra <- unlist(list(targets_spectra), recursive = TRUE)


  # It was tricky to apply the symbol transformation to a list whilst constructing
  #  a list structure that could be used correctly by merge_processed_spectra()
  # Thankfully, @wlandau suggested an awesome solution to a similar problem
  # https://github.com/ropensci/targets/discussions/461#discussioncomment-709984
  #
  # which will create list(fast_processed, slow_processed) from
  #  targets_spectra = c(fast_target_factory, slow_target_factory)
  name_processed <- tarchetypes::tar_select_names(targets_spectra, targets::ends_with("_processed"))
  processed_expr <- as.call(c(as.symbol("c"), lapply(name_processed, as.symbol)))


  name_fm <- paste0(name, "_fm_interpolated")
  name_sim <- paste0(name, "_sim_interpolated")
  name_df <- paste0(name, "_df_interpolated")
  name_processed_metadata <- paste0(name, "_processed_metadata")
  name_clusters <- paste0(name, "_clusters")
  name_picked <- paste0(name, "_picked")


  sym_fm <- as.symbol(name_fm)
  sym_sim <- as.symbol(name_sim)
  sym_df <- as.symbol(name_df)
  sym_processed_metadata <- as.symbol(name_processed_metadata)
  sym_clusters <- as.symbol(name_clusters)

  list(
    targets::tar_target_raw(
      name = name_fm,
      command = substitute(merge_processed_spectra(processed_spectra),
        env = list(processed_spectra = processed_expr)
      )
    ),
    targets::tar_target_raw(
      name = name_sim,
      command = substitute(coop::tcosine(fm_interpolated),
        env = list(fm_interpolated = sym_fm)
      )
    ),
    targets::tar_target_raw(
      name = name_df,
      command = substitute(delineate_with_similarity(
        sim_matrix = sim_interpolated,
        threshold = threshold,
        method = "complete"),
        env = list(sim_interpolated = sym_sim, threshold = threshold)
      )
    ),
    targets::tar_target_raw(
      name = name_processed_metadata,
      command = substitute(
        dplyr::bind_rows(
          lapply(processed_spectra, `[[`, "metadata")),
        env = list(processed_spectra = processed_expr)
      ),
      iteration = "list"
    ),
    targets::tar_target_raw(
      name = name_clusters,
      command = substitute(
        set_reference_spectra(df_interpolated, processed_metadata),
        env = list(df_interpolated = sym_df, processed_metadata = sym_processed_metadata)
      )
    ),
    targets::tar_target_raw(
      name = name_picked,
      command = substitute(
        pick_spectra(cluster_df = df_interpolated,
                     metadata_df = metadata_df, criteria_column = criteria_column,
                     hard_mask_column = hard_mask_column,
                     soft_mask_column = soft_mask_column,
                     is_descending_order = is_descending_order,
                     is_sorted = is_sorted),
        env = list(df_interpolated = sym_clusters,
                     metadata_df = metadata_df, criteria_column = criteria_column,
                     hard_mask_column = hard_mask_column,
                     soft_mask_column = soft_mask_column,
                     is_descending_order = is_descending_order,
                     is_sorted = is_sorted
                   )
      )
    )
  )
}
